version: 2
updates:
  # Maintain GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "ci(deps)"
    groups:
      github-actions:
        patterns:
          - "*"

  # Maintain Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "deps(python)"
    open-pull-requests-limit: 10
    groups:
      python-dependencies:
        patterns:
          - "*"

  # Maintain Frontend web dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "deps(frontend)"
    open-pull-requests-limit: 10
    groups:
      npm-dependencies:
        patterns:
          - "*"

  # Maintain Frontend tests dependencies
  - package-ecosystem: "npm"
    directory: "/tests/frontend_tests"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "deps(frontend-tests)"
    open-pull-requests-limit: 5

  # Maintain Frontend E2E tests dependencies
  - package-ecosystem: "npm"
    directory: "/tests/frontend_tests/e2e"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "deps(frontend-e2e)"
    open-pull-requests-limit: 5

  # Maintain Dockerfile dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    commit-message:
      prefix: "ci(docker)"
