version: "3.9"
services:
  api:
    build: { context: ./base, dockerfile: Dockerfile }
    env_file: [./docker/.env.prod]
    environment:
      DEVICE: "cpu"
      UI_MOUNT_ENABLED: "true"
      UI_STATIC_DIR: "/app/static"
    deploy: {}
